# Generated by Django 5.1.2 on 2024-11-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
