# Generated by Django 5.1.2 on 2024-11-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_service_name_presentationimage_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='team',
            field=models.IntegerField(unique=True),
        ),
    ]
