# Generated by Django 5.1.2 on 2024-11-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_thumnail_image_service_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='team',
            field=models.IntegerField(),
        ),
    ]
