# Generated by Django 5.1.2 on 2024-11-07 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_service_team_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('members', models.TextField()),
                ('part', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='team_members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.team'),
        ),
    ]
