# Generated by Django 5.1.2 on 2024-11-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_team_service_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='part',
        ),
        migrations.AddField(
            model_name='service',
            name='team_part',
            field=models.TextField(blank=True, null=True),
        ),
    ]
