# Generated by Django 5.1.2 on 2024-11-07 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_team_part_service_team_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='team_members',
        ),
        migrations.RemoveField(
            model_name='service',
            name='team_part',
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('member', models.CharField(max_length=30)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('part', models.CharField(max_length=30)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part', to='services.service')),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
