# Generated by Django 5.1.2 on 2024-11-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_remove_service_team_members_remove_service_team_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='part',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
