# Generated by Django 5.1.2 on 2024-11-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_member_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='intro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
