# Generated by Django 5.1.2 on 2024-11-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_service_intro_delete_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='team',
            field=models.IntegerField(default=21, unique=True),
        ),
    ]
