# Generated by Django 5.1.2 on 2024-11-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='writer',
            field=models.CharField(max_length=30),
        ),
    ]
