# Generated by Django 5.1.2 on 2024-11-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='team',
        ),
    ]
